# Chart Testing Configuration
helm-extra-args: --timeout 600s
chart-dirs:
  - .
chart-repos:
  - cnpg=https://cloudnative-pg.github.io/charts
  - altinity=https://helm.altinity.com/
check-version-increment: false
validate-maintainers: true
validate-chart-schema: false
validate-yaml: true
exclude-deprecated: true
lint-conf: .github/lintconf.yaml
target-branch: main
